package com.tedu.mapper.generatorMapper;

import com.tedu.common.Inventory;
import com.tedu.common.InventoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InventoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    int countByExample(InventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    int deleteByExample(InventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    int deleteByPrimaryKey(Integer proid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    int insert(Inventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    int insertSelective(Inventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    List<Inventory> selectByExample(InventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    Inventory selectByPrimaryKey(Integer proid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    int updateByExampleSelective(@Param("record") Inventory record, @Param("example") InventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    int updateByExample(@Param("record") Inventory record, @Param("example") InventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    int updateByPrimaryKeySelective(Inventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    int updateByPrimaryKey(Inventory record);
}