package com.tedu.mapper.generatorMapper;

import entity.Supply;
import entity.SupplyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SupplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supply
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    int countByExample(SupplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supply
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    int deleteByExample(SupplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supply
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    int deleteByPrimaryKey(Integer supId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supply
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    int insert(Supply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supply
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    int insertSelective(Supply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supply
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    List<Supply> selectByExample(SupplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supply
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    Supply selectByPrimaryKey(Integer supId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supply
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    int updateByExampleSelective(@Param("record") Supply record, @Param("example") SupplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supply
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    int updateByExample(@Param("record") Supply record, @Param("example") SupplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supply
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    int updateByPrimaryKeySelective(Supply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supply
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    int updateByPrimaryKey(Supply record);
}