spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_pss?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

