package com.tedu.common;

import java.math.BigDecimal;
import java.util.Date;

public class Cusretire {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cusretire.saleid
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private Integer saleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cusretire.proid
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private Integer proid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cusretire.pname
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private String pname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cusretire.price
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cusretire.num
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cusretire.total
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private BigDecimal total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cusretire.sale_date
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private Date saleDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cusretire.retdate
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private Date retdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cusretire.reason
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cusretire.marks
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private String marks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cusretire.saleid
     *
     * @return the value of cusretire.saleid
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public Integer getSaleid() {
        return saleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cusretire.saleid
     *
     * @param saleid the value for cusretire.saleid
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setSaleid(Integer saleid) {
        this.saleid = saleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cusretire.proid
     *
     * @return the value of cusretire.proid
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public Integer getProid() {
        return proid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cusretire.proid
     *
     * @param proid the value for cusretire.proid
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setProid(Integer proid) {
        this.proid = proid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cusretire.pname
     *
     * @return the value of cusretire.pname
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cusretire.pname
     *
     * @param pname the value for cusretire.pname
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setPname(String pname) {
        this.pname = pname == null ? null : pname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cusretire.price
     *
     * @return the value of cusretire.price
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cusretire.price
     *
     * @param price the value for cusretire.price
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cusretire.num
     *
     * @return the value of cusretire.num
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cusretire.num
     *
     * @param num the value for cusretire.num
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cusretire.total
     *
     * @return the value of cusretire.total
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public BigDecimal getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cusretire.total
     *
     * @param total the value for cusretire.total
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cusretire.sale_date
     *
     * @return the value of cusretire.sale_date
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public Date getSaleDate() {
        return saleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cusretire.sale_date
     *
     * @param saleDate the value for cusretire.sale_date
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setSaleDate(Date saleDate) {
        this.saleDate = saleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cusretire.retdate
     *
     * @return the value of cusretire.retdate
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public Date getRetdate() {
        return retdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cusretire.retdate
     *
     * @param retdate the value for cusretire.retdate
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setRetdate(Date retdate) {
        this.retdate = retdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cusretire.reason
     *
     * @return the value of cusretire.reason
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cusretire.reason
     *
     * @param reason the value for cusretire.reason
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cusretire.marks
     *
     * @return the value of cusretire.marks
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public String getMarks() {
        return marks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cusretire.marks
     *
     * @param marks the value for cusretire.marks
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setMarks(String marks) {
        this.marks = marks == null ? null : marks.trim();
    }
}