package com.tedu.common;

public class Custom {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.cusid
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private Integer cusid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.cusname
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private String cusname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.tel
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.staff_id
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private String staffId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.address
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.email
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.cusid
     *
     * @return the value of custom.cusid
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public Integer getCusid() {
        return cusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.cusid
     *
     * @param cusid the value for custom.cusid
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setCusid(Integer cusid) {
        this.cusid = cusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.cusname
     *
     * @return the value of custom.cusname
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public String getCusname() {
        return cusname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.cusname
     *
     * @param cusname the value for custom.cusname
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setCusname(String cusname) {
        this.cusname = cusname == null ? null : cusname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.tel
     *
     * @return the value of custom.tel
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.tel
     *
     * @param tel the value for custom.tel
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.staff_id
     *
     * @return the value of custom.staff_id
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public String getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.staff_id
     *
     * @param staffId the value for custom.staff_id
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setStaffId(String staffId) {
        this.staffId = staffId == null ? null : staffId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.address
     *
     * @return the value of custom.address
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.address
     *
     * @param address the value for custom.address
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.email
     *
     * @return the value of custom.email
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.email
     *
     * @param email the value for custom.email
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }
}