package com.tedu.common;

public class Inventory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.proid
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private Integer proid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.pname
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private String pname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.num
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.marks
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private String marks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.proid
     *
     * @return the value of inventory.proid
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public Integer getProid() {
        return proid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.proid
     *
     * @param proid the value for inventory.proid
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setProid(Integer proid) {
        this.proid = proid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.pname
     *
     * @return the value of inventory.pname
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.pname
     *
     * @param pname the value for inventory.pname
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setPname(String pname) {
        this.pname = pname == null ? null : pname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.num
     *
     * @return the value of inventory.num
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.num
     *
     * @param num the value for inventory.num
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.marks
     *
     * @return the value of inventory.marks
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public String getMarks() {
        return marks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.marks
     *
     * @param marks the value for inventory.marks
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setMarks(String marks) {
        this.marks = marks == null ? null : marks.trim();
    }
}