package com.tedu.common;

import java.math.BigDecimal;
import java.util.Date;

public class Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.proid
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private Integer proid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pname
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private String pname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.price
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.inprice
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private BigDecimal inprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.prodate
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private Date prodate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.reledate
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private Date reledate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.supname
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private String supname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.protype
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private String protype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.unit
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.marks
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private String marks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.proid
     *
     * @return the value of product.proid
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public Integer getProid() {
        return proid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.proid
     *
     * @param proid the value for product.proid
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setProid(Integer proid) {
        this.proid = proid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pname
     *
     * @return the value of product.pname
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pname
     *
     * @param pname the value for product.pname
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setPname(String pname) {
        this.pname = pname == null ? null : pname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.price
     *
     * @return the value of product.price
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.price
     *
     * @param price the value for product.price
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.inprice
     *
     * @return the value of product.inprice
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public BigDecimal getInprice() {
        return inprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.inprice
     *
     * @param inprice the value for product.inprice
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setInprice(BigDecimal inprice) {
        this.inprice = inprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.prodate
     *
     * @return the value of product.prodate
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public Date getProdate() {
        return prodate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.prodate
     *
     * @param prodate the value for product.prodate
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setProdate(Date prodate) {
        this.prodate = prodate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.reledate
     *
     * @return the value of product.reledate
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public Date getReledate() {
        return reledate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.reledate
     *
     * @param reledate the value for product.reledate
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setReledate(Date reledate) {
        this.reledate = reledate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.supname
     *
     * @return the value of product.supname
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public String getSupname() {
        return supname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.supname
     *
     * @param supname the value for product.supname
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setSupname(String supname) {
        this.supname = supname == null ? null : supname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.protype
     *
     * @return the value of product.protype
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public String getProtype() {
        return protype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.protype
     *
     * @param protype the value for product.protype
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setProtype(String protype) {
        this.protype = protype == null ? null : protype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.unit
     *
     * @return the value of product.unit
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.unit
     *
     * @param unit the value for product.unit
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.marks
     *
     * @return the value of product.marks
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public String getMarks() {
        return marks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.marks
     *
     * @param marks the value for product.marks
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setMarks(String marks) {
        this.marks = marks == null ? null : marks.trim();
    }
}