package com.tedu.common;

import java.util.Date;

public class Retire {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column retire.id
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column retire.proid
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private Integer proid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column retire.pname
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private String pname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column retire.num
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column retire.indate
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private Date indate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column retire.retdate
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private Date retdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column retire.reason
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column retire.marks
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private String marks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column retire.id
     *
     * @return the value of retire.id
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column retire.id
     *
     * @param id the value for retire.id
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column retire.proid
     *
     * @return the value of retire.proid
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public Integer getProid() {
        return proid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column retire.proid
     *
     * @param proid the value for retire.proid
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setProid(Integer proid) {
        this.proid = proid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column retire.pname
     *
     * @return the value of retire.pname
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column retire.pname
     *
     * @param pname the value for retire.pname
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setPname(String pname) {
        this.pname = pname == null ? null : pname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column retire.num
     *
     * @return the value of retire.num
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column retire.num
     *
     * @param num the value for retire.num
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column retire.indate
     *
     * @return the value of retire.indate
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public Date getIndate() {
        return indate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column retire.indate
     *
     * @param indate the value for retire.indate
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setIndate(Date indate) {
        this.indate = indate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column retire.retdate
     *
     * @return the value of retire.retdate
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public Date getRetdate() {
        return retdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column retire.retdate
     *
     * @param retdate the value for retire.retdate
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setRetdate(Date retdate) {
        this.retdate = retdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column retire.reason
     *
     * @return the value of retire.reason
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column retire.reason
     *
     * @param reason the value for retire.reason
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column retire.marks
     *
     * @return the value of retire.marks
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public String getMarks() {
        return marks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column retire.marks
     *
     * @param marks the value for retire.marks
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setMarks(String marks) {
        this.marks = marks == null ? null : marks.trim();
    }
}