package com.tedu.common;

import java.math.BigDecimal;
import java.util.Date;

public class Sale {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.saleid
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private Integer saleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.proid
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private Integer proid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.price
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.num
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.total
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private BigDecimal total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.sale_date
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private Date saleDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.cusid
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private Date cusid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.marks
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private String marks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.status
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.saleid
     *
     * @return the value of sale.saleid
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public Integer getSaleid() {
        return saleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.saleid
     *
     * @param saleid the value for sale.saleid
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setSaleid(Integer saleid) {
        this.saleid = saleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.proid
     *
     * @return the value of sale.proid
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public Integer getProid() {
        return proid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.proid
     *
     * @param proid the value for sale.proid
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setProid(Integer proid) {
        this.proid = proid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.price
     *
     * @return the value of sale.price
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.price
     *
     * @param price the value for sale.price
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.num
     *
     * @return the value of sale.num
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.num
     *
     * @param num the value for sale.num
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.total
     *
     * @return the value of sale.total
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public BigDecimal getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.total
     *
     * @param total the value for sale.total
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.sale_date
     *
     * @return the value of sale.sale_date
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public Date getSaleDate() {
        return saleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.sale_date
     *
     * @param saleDate the value for sale.sale_date
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setSaleDate(Date saleDate) {
        this.saleDate = saleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.cusid
     *
     * @return the value of sale.cusid
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public Date getCusid() {
        return cusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.cusid
     *
     * @param cusid the value for sale.cusid
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setCusid(Date cusid) {
        this.cusid = cusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.marks
     *
     * @return the value of sale.marks
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public String getMarks() {
        return marks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.marks
     *
     * @param marks the value for sale.marks
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setMarks(String marks) {
        this.marks = marks == null ? null : marks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.status
     *
     * @return the value of sale.status
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.status
     *
     * @param status the value for sale.status
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}