package com.tedu.common;

public class Staff {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.staff_id
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private Integer staffId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.staff_name
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private String staffName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.staff_num
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private Integer staffNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.gender
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.tel
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.staff_type
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private String staffType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.pwd
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private String pwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.shop_id
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private String shopId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.staff_id
     *
     * @return the value of staff.staff_id
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public Integer getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.staff_id
     *
     * @param staffId the value for staff.staff_id
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setStaffId(Integer staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.staff_name
     *
     * @return the value of staff.staff_name
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public String getStaffName() {
        return staffName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.staff_name
     *
     * @param staffName the value for staff.staff_name
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setStaffName(String staffName) {
        this.staffName = staffName == null ? null : staffName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.staff_num
     *
     * @return the value of staff.staff_num
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public Integer getStaffNum() {
        return staffNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.staff_num
     *
     * @param staffNum the value for staff.staff_num
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setStaffNum(Integer staffNum) {
        this.staffNum = staffNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.gender
     *
     * @return the value of staff.gender
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.gender
     *
     * @param gender the value for staff.gender
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.tel
     *
     * @return the value of staff.tel
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.tel
     *
     * @param tel the value for staff.tel
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.staff_type
     *
     * @return the value of staff.staff_type
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public String getStaffType() {
        return staffType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.staff_type
     *
     * @param staffType the value for staff.staff_type
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setStaffType(String staffType) {
        this.staffType = staffType == null ? null : staffType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.pwd
     *
     * @return the value of staff.pwd
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.pwd
     *
     * @param pwd the value for staff.pwd
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.shop_id
     *
     * @return the value of staff.shop_id
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public String getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.shop_id
     *
     * @param shopId the value for staff.shop_id
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setShopId(String shopId) {
        this.shopId = shopId == null ? null : shopId.trim();
    }
}