package com.tedu.common;

import java.util.Date;

public class Stock {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.id
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.proid
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private Integer proid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.pname
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private String pname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.num
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.indate
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private Date indate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.marks
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private String marks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.id
     *
     * @return the value of stock.id
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.id
     *
     * @param id the value for stock.id
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.proid
     *
     * @return the value of stock.proid
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public Integer getProid() {
        return proid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.proid
     *
     * @param proid the value for stock.proid
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setProid(Integer proid) {
        this.proid = proid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.pname
     *
     * @return the value of stock.pname
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.pname
     *
     * @param pname the value for stock.pname
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setPname(String pname) {
        this.pname = pname == null ? null : pname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.num
     *
     * @return the value of stock.num
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.num
     *
     * @param num the value for stock.num
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.indate
     *
     * @return the value of stock.indate
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public Date getIndate() {
        return indate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.indate
     *
     * @param indate the value for stock.indate
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setIndate(Date indate) {
        this.indate = indate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.marks
     *
     * @return the value of stock.marks
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public String getMarks() {
        return marks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.marks
     *
     * @param marks the value for stock.marks
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setMarks(String marks) {
        this.marks = marks == null ? null : marks.trim();
    }
}