package com.tedu.common;

public class Supply {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supply.sup_id
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private Integer supId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supply.sup_name
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private String supName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supply.tel
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supply.staff_id
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private String staffId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supply.address
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supply.email
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supply.sup_id
     *
     * @return the value of supply.sup_id
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public Integer getSupId() {
        return supId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supply.sup_id
     *
     * @param supId the value for supply.sup_id
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setSupId(Integer supId) {
        this.supId = supId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supply.sup_name
     *
     * @return the value of supply.sup_name
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public String getSupName() {
        return supName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supply.sup_name
     *
     * @param supName the value for supply.sup_name
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setSupName(String supName) {
        this.supName = supName == null ? null : supName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supply.tel
     *
     * @return the value of supply.tel
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supply.tel
     *
     * @param tel the value for supply.tel
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supply.staff_id
     *
     * @return the value of supply.staff_id
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public String getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supply.staff_id
     *
     * @param staffId the value for supply.staff_id
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setStaffId(String staffId) {
        this.staffId = staffId == null ? null : staffId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supply.address
     *
     * @return the value of supply.address
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supply.address
     *
     * @param address the value for supply.address
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supply.email
     *
     * @return the value of supply.email
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supply.email
     *
     * @param email the value for supply.email
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }
}