package com.tedu.common;

public class Type {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.pro_type
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private Integer proType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.type_name
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    private String typeName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type.pro_type
     *
     * @return the value of type.pro_type
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public Integer getProType() {
        return proType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type.pro_type
     *
     * @param proType the value for type.pro_type
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setProType(Integer proType) {
        this.proType = proType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type.type_name
     *
     * @return the value of type.type_name
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type.type_name
     *
     * @param typeName the value for type.type_name
     *
     * @mbggenerated Mon Jun 27 09:02:48 CST 2022
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }
}